export const Data = [
  {
    id: 1,
    title: 'Voosh Outlet 1',
    category: 'vegan',
    desc: 'vegan products',
    price: 30,
  },
  {
    id: 2,
    title: 'Voosh Outlet 2',
    category: 'vegan',
    desc: 'vegan products',
    price: 230,
  },
  {
    id: 3,
    title: 'Voosh Outlet 3',
    category: 'veg',
    desc: 'veg products',
    price: 130,
  },
  {
    id: 4,
    title: 'Voosh Outlet 4',
    category: 'Meat',
    desc: 'Meat products',
    price: 500,
  },
  {
    id: 5,
    title: 'Voosh Outlet 5',
    category: 'vegan',
    desc: 'vegan products',
    price: 350,
  },
  {
    id: 6,
    title: 'Voosh Outlet 6',
    category: 'North Indian',
    desc: 'North Indian products',
    price: 430,
  },
  {
    id: 7,
    title: 'Voosh Outlet 7',
    category: 'Italian',
    desc: 'Italian products',
    price: 650,
  },
  {
    id: 8,
    title: 'Voosh Outlet 8',
    category: 'vegan',
    desc: 'vegan products',
    price: 30,
  },
  {
    id: 9,
    title: 'Voosh Outlet 9',
    category: 'chinese',
    desc: 'chinese products',
    price: 30,
  },
  {
    id: 10,
    title: 'Voosh Outlet 10',
    category: 'Beverages',
    desc: 'soft Drinks',
    price: 30,
  },
];
